service: volume-grabber

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 180
  environment:
    TAAPI_API_KEY: ${env:TAAPI_API_KEY}
    NTFY_TOPIC: ${env:NTFY_TOPIC}

functions:
  analyze:
    handler: src.main.handler
    events:
      - schedule: rate(15 minutes)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: volume-grabber-deps
      description: Dependencies for volume grabber 